#!/usr/bin/env bash
# installs nginx and sets the index.html file
sudo apt-get update
sudo apt-get install nginx -y

# Creates a string in index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Restarts nginx service
sudo service nginx restart
