#!/usr/bin/env bash
# installs nginx and sets the index.html file
apt-get update
apt-get -y install nginx
sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
service nginx restart
