#!/usr/bin/env bash
# redirection
sudo apt-get update
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
# Prints Holberton School
echo "Holberton School" | sudo tee /var/www/html/index.html
# Rewrites
command='\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "42i$command" /etc/nginx/sites-available/default

# Restarts
sudo service nginx restart
